services:
  api:
    build:
      context: .
    expose:
      - 8000
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api
    restart: always
