# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#
# AUTHOR: William A. Morris
# CREATION_DATE: 2024-08-28
# PURPOSE:
#   whenever new code is pushed to the main branch, this file will execute the following steps
#   in order to publish this application as a Docker Container on Dockerhub
#   - run unit tests
#   - build the project and create a Java ARchive (JAR)
#   - create Docker Container from generated application artifacts
#   - publish container

name: Test, Build, Publish

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build App
      run: |
        aws codeartifact login --tool pip --domain morriswa-org --repository morriswa-central
        pip install .
        python setup.py build

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: morriswa
        password: ${{ secrets.DOCKERPASSWORD }}
      
    - name: Build and Publish to Docker Hub
      run: |
        cd ./build
        docker build . -t morriswa/cmx-battleship-online-api:latest
        docker push morriswa/cmx-battleship-online-api:latest
