# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#
# AUTHOR: William A. Morris
# CREATION_DATE: 2024-08-28
# PURPOSE:
#   whenever new code is pushed to the main branch, this file will execute the following steps
#   in order to publish this application as a Docker Container on Dockerhub
#   - run unit tests
#   - build the project and create a Java ARchive (JAR)
#   - create Docker Container from generated application artifacts
#   - publish container

name: Test, Build, Publish

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: morriswa
        password: ${{ secrets.DOCKERPASSWORD }}
      
    - name: Build and Publish to Docker Hub
      run: |
        export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
        export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
        export AWS_DEFAULT_REGION=us-east-2

        docker build \
          --secret id=AWS_ACCESS_KEY_ID \
          --secret id=AWS_SECRET_ACCESS_KEY \
          --secret id=AWS_DEFAULT_REGION \
          . -t morriswa/cmx-battleship-online-api:latest
        docker push morriswa/cmx-battleship-online-api:latest
